[package]
name = "datetime"
description = "Library for date and time formatting and arithmetic"

authors = [ "ogham@bsago.me" ]
documentation = "http://bsago.me/doc/datetime/"
homepage = "https://github.com/ogham/rust-datetime"
license = "MIT"
readme = "README.md"
version = "0.2.1"

[lib]
name = "datetime"
doctest = false

[dependencies]
locale = "0.1"
num = "*"
pad = "0.1"
regex = "0.1"
tz = "0.2"
libc = "0.1"
