[package]
name = "datetime"
description = "Library for date and time formatting and arithmetic"

authors = [ "ogham@bsago.me" ]
documentation = "http://bsago.me/doc/datetime/"
homepage = "https://github.com/ogham/rust-datetime"
license = "MIT"
readme = "README.md"
version = "0.1.4"

[lib]
name = "datetime"
doctest = false

[dependencies]
pad = "0.1.1"
locale = "0.1.4"
regex = "0.1.16"
regex_macros = "0.1.10"

#[dev-dependencies.datetime_macros]
#path = "datetime-macros"
#version = "0.1.2"

