[package]
name = "datetime"
description = "Library for date and time formatting and arithmetic"

authors = [ "ogham@bsago.me", "Hendrik Sollich <hendrik@hoodie.de>" ]
documentation = "http://datetime.rustdocs.org/datetime/"
homepage = "https://github.com/rust-datetime/datetime"
license = "MIT"
readme = "README.md"
version = "0.4.1"

[lib]
name = "datetime"

[dependencies]
locale = "0.1"
num = "*"
pad = "0.1"
libc = "0.1"
lazy_static = "0.1.*"
iso8601 = "0.1.0"


[dev-dependencies]
rustc-serialize = "0.3"
regex = "0.1"
